### ISSUE TITLE
parallel threads by lmsasm

### ISSUE THREAD

**Issue by AnarCom** [ev3dev/lmsasm#7]
I'm staring using your compiler for lms VM (lmsasm). And i cannot understand how to start parallel thread because there no information about it in guides. Can you help me whith this problem?

**Comment by dlech** [comment]
It depends on what you mean by parallel threads. And technically speaking, we should probably say "tasks" instead of "threads" if we want to use the textbook definitions. The lms2012 VM is implemented as a single threaded event loop, so we aren't actually using operating system threads.

In lmsasm, there are 3 kinds of "objects" (name comes from official LEGO firmware source code). They are `vmthread`, `subcall` and `block`.

### vmthread

The most basic is `vmthread`. Each `vmthread` is a task that can be scheduled concurrently with other tasks. The first object in a program must be a `vmthread` and serves as an entry point. There are also some VM instructions for manipulating `vmthreads`. `OBJECT_START`, `OBJECT_STOP` and `OBJECT_WAIT`.

So a simple example might look like this:

```
vmthread main {
    OBJECT_START(task1)
    OBJECT_START(task2)
    OBJECT_START(task3)
    OBJECT_WAIT(task1)
    OBJECT_WAIT(task2)
    OBJECT_WAIT(task3)
}

vmthread task1 {
    // do stuff
}

vmthread task2 {
    // do stuff
}

vmthread task3 {
    // do stuff
}
```

This should start 3 parallel tasks and then wait until all 3 tasks have ended before ending the program.

### subcall

`subcall`s are subroutines or functions. Unlike other object types, they can take parameters. Also, they are blocking, so can't be used by themselves to create parallel tasks.

Example:

```
vmthread main {
    CALL(myFunc,0)
    CALL(myFunc,1)
}

subcall myFunc {
    IN_32 arg

    // do stuff
}
```

This should call `myFunc` with `arg` set to 0, wait for the `subcall` to finish, call it again with `arg` set to 1, then end the program.

### block

`block`s are used to "fork" a task. This is a bit different from forking a process in C programming, but similar enough to call it that in the same way that we mean "tasks" when we say "threads". Currently the compiler doesn't have very good support for `block`s (see #5). Blocks are different from `vmthread`s in that they share their local variables with the task that calls the `block` object. `block` objects also have a trigger count. I haven't figured out a practical use for this yet though. Still, we have to use `OBJECT_TRIG` instead of `OBJECT_START` to begin `block` objects.



```
vmthread main {
    DATA32 myVar

    // do stuff
    OBJECT_TRIG(task1)
    OBJECT_TRIG(task2)
    OBJECT_WAIT(task1)
    OBJECT_WAIT(task2)
    // do more stuff
}

block task1 {
    // Because of lack of compiler support, local variables have to match vmthread main exactly!
    DATA32 myVar

    // do stuff
}

block task2 {
    // Because of lack of compiler support, local variables have to match vmthread main exactly!
    DATA32 myVar

    // do stuff
}
```

This works similar to the first example except that local variables are shared. If we change `myVar` in `task1`, it is also changed in `main` and `task2`.

**Comment by dlech** [comment]
Another tip I have learned is that one must be cautious about using `OBJECT_STOP`. If you have a task that calls a subroutine and then stop the task while the subroutine is running, the task will continue when the subroutine returns even though it was "stopped".

**Comment by iCheh** [comment]
Hello.
Are there any changes in using a block object in a program?
